#Requires -Version 5.1
<#
.SYNOPSIS
    Generates INDEX.md — a structured file inventory of the repository.
.DESCRIPTION
    Scans the repo, collects file metadata (path, line count, size), and writes
    a markdown index grouped by directory. Purpose annotations come from an
    embedded lookup table with .SYNOPSIS fallback for PowerShell files.
.PARAMETER RepoRoot
    Repository root directory. Defaults to one level above this script.
#>
param(
    [string]$RepoRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Resolve repo root ───────────────────────────────────────────────────────
if (-not $RepoRoot) {
    $RepoRoot = Split-Path -Parent $PSScriptRoot
}
$RepoRoot = (Resolve-Path $RepoRoot).Path

# ── Annotations lookup ──────────────────────────────────────────────────────
$Annotations = @{
    'install.ps1'                    = 'irm|iex entry point -- downloads repo, verifies manifest, launches bootstrap'
    'bootstrap.ps1'                  = 'Sets up scheduled tasks, state file, launches monitor + orchestrator'
    'uninstall.ps1'                  = 'Removes all WinDeploy components (force-kills processes first)'
    'lint.ps1'                       = 'PSScriptAnalyzer + custom PS 5.1 / task / path / state checks'
    'manifest.json'                  = 'Auto-generated by CI -- file hashes and repo metadata'
    'manifest.sig'                   = 'GPG detached signature of manifest.json'
    'CLAUDE.md'                      = 'AI-assisted development context and conventions'
    'README.md'                      = 'Project overview and usage documentation'
    'INDEX.md'                       = 'Auto-generated file inventory (this file)'
    '.gitignore'                     = 'Git ignore rules for binaries, logs, and state'
    'core/Config.psm1'              = 'Shared constants ($WD.*) -- single source of truth for paths and stage order'
    'core/State.psm1'               = 'State.json read/write, reboot counter, stage tracking'
    'core/Logging.psm1'             = 'Write-LogInfo/Success/Warning/Error + concurrent-safe file output'
    'core/Resilience.psm1'          = 'Task self-healing, directory ACLs, state quarantine, watchdog'
    'core/Orchestrator.ps1'         = 'Master controller -- runs stages in order, handles reboots'
    'core/Monitor.ps1'              = 'WPF progress window with stage list, Tailscale QR, error panel'
    'core/Notify.ps1'               = 'Tray notification on deployment completion, self-removes'
    'core/Notify-Webhook.ps1'       = 'Webhook notification for deployment events'
    'core/Diagnostic.ps1'           = 'Standalone diagnostic and troubleshooting tool'
    'core/PowerSettings.ps1'        = 'Stage 1: power plan, sleep, and display timeout settings'
    'core/Debloat.ps1'              = 'Stage 2: remove bloatware apps from bloatware.json lists'
    'core/WinTweaks.ps1'            = 'Stage 3: registry tweaks, dark theme, DPI, Chrome, WinUtil preset'
    'core/AppInstall.ps1'           = 'Stages 4-5: Dell SupportAssist and Power Manager installs'
    'core/Tailscale.ps1'            = 'Stage 6: Tailscale install + QR-based registration'
    'core/WindowsUpdate.ps1'        = 'Stage 7: Windows Update (last -- multiple reboots expected)'
    'core/Cleanup.ps1'              = 'Stage 8: remove tasks, disable auto-logon, final reboot'
    'config/settings.json'          = 'All deployment configuration -- edit this, not the scripts'
    'config/winutil-preset.json'    = 'WinUtil tweak IDs applied during WinTweaks stage'
    'data/bloatware.json'           = 'Safe and optional app removal lists for Debloat stage'
    'data/profiles.json'            = 'Deployment profile definitions'
    'docs/gpg-setup.md'             = 'Instructions for generating GPG key pair for manifest signing'
    '.github/workflows/ci.yml'      = 'CI pipeline: lint, validate tasks, sign manifest (sequential)'
    'apps/.gitkeep'                 = 'Placeholder -- apps/ holds downloaded installers at runtime'
    'tools/Update-Index.ps1'        = 'Generates INDEX.md file inventory (this script)'
    '.githooks/pre-commit'          = 'Git pre-commit shim -- calls pre-commit.ps1'
    '.githooks/pre-commit.ps1'      = 'Pre-commit hook logic -- regenerates and stages INDEX.md'
}

# ── Exclusion patterns (match .gitignore) ───────────────────────────────────
function Test-Excluded {
    param([string]$RelPath)
    if ($RelPath -like '.git\*' -or $RelPath -like '.git/*') { return $true }
    if ($RelPath -like 'apps\*.exe' -or $RelPath -like 'apps/*.exe') { return $true }
    if ($RelPath -like 'apps\*.msi' -or $RelPath -like 'apps/*.msi') { return $true }
    if ($RelPath -like 'apps\*.msix' -or $RelPath -like 'apps/*.msix') { return $true }
    if ($RelPath -like 'logs\*' -or $RelPath -like 'logs/*') { return $true }
    if ($RelPath -eq 'state.json') { return $true }
    return $false
}

# ── Extract .SYNOPSIS from PowerShell files ─────────────────────────────────
function Get-Synopsis {
    param([string]$FilePath)
    try {
        $lines = [System.IO.File]::ReadAllLines($FilePath)
    } catch {
        return $null
    }
    $inSynopsis = $false
    $synopsis = ''
    foreach ($line in $lines) {
        if ($line -match '^\s*\.SYNOPSIS\s*$') {
            $inSynopsis = $true
            continue
        }
        if ($inSynopsis) {
            if ($line -match '^\s*\.' -or $line -match '^\s*#>') {
                break
            }
            $text = $line.Trim()
            if ($text) {
                $synopsis = $text
                break
            }
        }
    }
    if ($synopsis) { return $synopsis }
    return $null
}

# ── Scan files ──────────────────────────────────────────────────────────────
$files = Get-ChildItem -Path $RepoRoot -Recurse -File | Where-Object {
    $rel = $_.FullName.Substring($RepoRoot.Length + 1)
    -not (Test-Excluded $rel)
} | Sort-Object { $_.DirectoryName }, { $_.Name }

$entries = @()
$totalLines = 0
$totalPsLines = 0
$psFileCount = 0
$totalSize = 0

foreach ($f in $files) {
    $rel = $f.FullName.Substring($RepoRoot.Length + 1).Replace('\', '/')

    # Line count for text files; also compute LF-normalized size for consistency
    # across platforms (CRLF on Windows vs LF on CI/Linux).
    $lineCount = $null
    $size = $f.Length
    $textExts = @('.ps1', '.psm1', '.json', '.yml', '.yaml', '.md', '.txt', '')
    if ($textExts -contains $f.Extension.ToLower()) {
        try {
            $raw = [System.IO.File]::ReadAllText($f.FullName)
            $normalized = $raw -replace "`r`n", "`n"
            $size = [System.Text.Encoding]::UTF8.GetByteCount($normalized)
            $lineCount = ($normalized -split "`n").Count
        } catch {
            $lineCount = $null
        }
    }
    $totalSize += $size

    if ($f.Extension -in @('.ps1', '.psm1')) {
        $psFileCount++
        if ($lineCount) { $totalPsLines += $lineCount }
    }
    if ($lineCount) { $totalLines += $lineCount }

    # Purpose annotation
    $purpose = $null
    if ($Annotations.ContainsKey($rel)) {
        $purpose = $Annotations[$rel]
    } elseif ($f.Extension -in @('.ps1', '.psm1')) {
        $purpose = Get-Synopsis $f.FullName
    }
    if (-not $purpose) { $purpose = '--' }

    # Format size
    if ($size -ge 1024) {
        $sizeStr = '{0:N1} KB' -f ($size / 1024)
    } else {
        $sizeStr = "$size B"
    }

    $lineStr = if ($lineCount) { "$lineCount" } else { '--' }

    $dir = if ($rel -like '*/*') { ($rel -split '/')[0] } else { '' }

    $entries += [PSCustomObject]@{
        Rel     = $rel
        Lines   = $lineStr
        Size    = $sizeStr
        Purpose = $purpose
        Dir     = $dir
        RawLine = $lineCount
    }
}

# ── Build INDEX.md ──────────────────────────────────────────────────────────
$timestamp = (Get-Date).ToString('yyyy-MM-ddTHH:mm:ss')
$totalSizeStr = if ($totalSize -ge 1048576) {
    '{0:N1} MB' -f ($totalSize / 1048576)
} else {
    '{0:N0} KB' -f ($totalSize / 1024)
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# Repository Index')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('> Auto-generated by `tools/Update-Index.ps1` -- do not edit by hand.')
[void]$sb.AppendLine("> Last updated: $timestamp")
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Summary')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('| Metric | Value |')
[void]$sb.AppendLine('|---|---|')
[void]$sb.AppendLine("| Files | $($entries.Count) |")
[void]$sb.AppendLine("| PowerShell | $psFileCount files, $($totalPsLines.ToString('N0')) lines |")
[void]$sb.AppendLine("| Total size | $totalSizeStr |")
[void]$sb.AppendLine('')
[void]$sb.AppendLine('## Files')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('| Path | Lines | Size | Purpose |')
[void]$sb.AppendLine('|---|---|---|---|')

$lastDir = $null
foreach ($e in $entries) {
    if ($null -ne $lastDir -and $e.Dir -ne $lastDir) {
        [void]$sb.AppendLine('| | | | |')
    }
    $lastDir = $e.Dir

    [void]$sb.AppendLine("| ``$($e.Rel)`` | $($e.Lines) | $($e.Size) | $($e.Purpose) |")
}
[void]$sb.AppendLine('')

# ── Write output ────────────────────────────────────────────────────────────
$outPath = Join-Path $RepoRoot 'INDEX.md'
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
# StringBuilder.AppendLine uses CRLF on Windows; normalize to LF so the
# output is identical on every platform and git diff stays clean.
$content = $sb.ToString() -replace "`r`n", "`n"
[System.IO.File]::WriteAllText($outPath, $content, $utf8NoBom)

Write-Host "INDEX.md updated: $($entries.Count) files, $($totalPsLines.ToString('N0')) PS lines, $totalSizeStr total" -ForegroundColor Green
